server {
    listen 8080;
    location / {
        proxy_pass https://storage.googleapis.com/subhajit-das-portfolio$request_uri;
        proxy_set_header Host storage.googleapis.com;
        proxy_set_header User-Agent "CloudRun-Portfolio";
        proxy_intercept_errors off;
    }
}
